name: docker
on:
  release:
    branches: [ "master" ]
    types: [ "published" ]
    tags: [ "v*" ]

# Actions
# docker/setup-buildx-action@v3 https://github.com/marketplace/actions/docker-setup-buildx
# docker/login-action@v3 https://github.com/marketplace/actions/docker-login
# docker/metadata-action@v5 https://github.com/marketplace/actions/docker-metadata-action
# docker/build-push-action@v6 https://github.com/marketplace/actions/build-and-push-docker-images

jobs:
  docker:
    name: Docker image
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set application version
        run: sed -i "s#@box_git_version@#${{ github.ref_name }}#" bin/*
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: "${{ github.repository }}"
          tags: "type=semver,pattern={{version}}"
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
